CREATE TABLE IF NOT EXISTS <?php echo DB_PREFIX; ?>AIInfo (
	Id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NameKey TEXT(8) NOT NULL,
	ControlClass TEXT NOT NULL,

	UNIQUE (NameKey(8))
) CHARACTER SET latin1 COLLATE latin1_general_cs;

CREATE TABLE IF NOT EXISTS <?php echo DB_PREFIX; ?>UserStats (
	UserId INT NOT NULL PRIMARY KEY,
	FirstGame INT UNSIGNED,
	LastGame INT UNSIGNED,
	GameCount INT UNSIGNED NOT NULL DEFAULT 0,
	WinningCount INT UNSIGNED NOT NULL DEFAULT 0,
	ModeratorCount INT UNSIGNED NOT NULL DEFAULT 0,
	LastOnline INT UNSIGNED NOT NULL,
	AIId INT UNSIGNED,

	FOREIGN KEY (AIId) REFERENCES <?php echo DB_PREFIX; ?>AIInfo(Id)
) CHARACTER SET latin1 COLLATE latin1_general_cs;


CREATE TABLE IF NOT EXISTS <?php echo DB_PREFIX; ?>Groups (
	Id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name TEXT NOT NULL,
	Created INT UNSIGNED NOT NULL,
	LastGame INT UNSIGNED,
	Creator INT NOT NULL,
	Leader INT NOT NULL,
	CurrentGame INT UNSIGNED,
	EnterKey TEXT(12) NOT NULL,

	UNIQUE (EnterKey(12)),
	FOREIGN KEY (Creator) REFERENCES <?php echo DB_PREFIX; ?>UserStats(UserId),
	FOREIGN KEY (Leader) REFERENCES <?php echo DB_PREFIX; ?>UserStats(UserId)
) CHARACTER SET latin1 COLLATE latin1_general_cs;

CREATE TABLE IF NOT EXISTS <?php echo DB_PREFIX; ?>Games (
	Id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	MainGroup INT UNSIGNED NOT NULL,
	Started INT UNSIGNED NOT NULL,
	Finished INT UNSIGNED,
	CurrentPhase VARCHAR(8) NOT NULL,
	CurrentDay INT(8) NOT NULL,
	RuleSet TEXT NOT NULL,
	Vars TEXT,	

	FOREIGN KEY (MainGroup) REFERENCES <?php echo DB_PREFIX; ?>Groups(Id)
) CHARACTER SET latin1 COLLATE latin1_general_cs;

ALTER TABLE <?php echo DB_PREFIX; ?>Groups ADD CONSTRAINT
	FOREIGN KEY (CurrentGame) 
	REFERENCES <?php echo DB_PREFIX; ?>Games(Id);

CREATE TABLE IF NOT EXISTS <?php echo DB_PREFIX; ?>User (
	GroupId INT UNSIGNED NOT NULL,
	UserId INT NOT NULL,
	Player INT UNSIGNED,

	PRIMARY KEY (GroupId, UserId),
	FOREIGN KEY (GroupId) REFERENCES <?php echo DB_PREFIX; ?>Groups(Id),
	FOREIGN KEY (UserId) REFERENCES <?php echo DB_PREFIX; ?>UserStats(UserId)
) CHARACTER SET latin1 COLLATE latin1_general_cs;

CREATE TABLE IF NOT EXISTS <?php echo DB_PREFIX; ?>Player (
	Id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Game INT UNSIGNED NOT NULL,
	User INT NOT NULL,
	Alive BOOLEAN NOT NULL DEFAULT TRUE,
	ExtraWolfLive BOOLEAN NOT NULL DEFAULT FALSE,
	Vars TEXT,

	UNIQUE (Game, User),
	FOREIGN KEY (Game) REFERENCES <?php echo DB_PREFIX; ?>Games(Id),
	FOREIGN KEY (User) REFERENCES <?php echo DB_PREFIX; ?>User(UserId)
) CHARACTER SET latin1 COLLATE latin1_general_cs;

ALTER TABLE <?php echo DB_PREFIX; ?>User ADD CONSTRAINT
	FOREIGN KEY (Player) 
	REFERENCES <?php echo DB_PREFIX; ?>Player(Id);

CREATE TABLE IF NOT EXISTS <?php echo DB_PREFIX; ?>Roles (
	Player INT UNSIGNED NOT NULL,
	RoleKey VARCHAR(8) NOT NULL,
	RoleIndex TINYINT UNSIGNED NOT NULL,
		
	PRIMARY KEY (Player, RoleKey(8)),
	FOREIGN KEY (Player) REFERENCES <?php echo DB_PREFIX; ?>Player(Id)
) CHARACTER SET latin1 COLLATE latin1_general_cs;

CREATE TABLE IF NOT EXISTS <?php echo DB_PREFIX; ?>VisibleRoles (
	Player INT UNSIGNED NOT NULL,
	Target INT UNSIGNED NOT NULL,
	RoleKey VARCHAR(8) NOT NULL,
	
	PRIMARY KEY (Player, Target, RoleKey(8)),
	FOREIGN KEY (Player) REFERENCES <?php echo DB_PREFIX; ?>Player(Id),
	FOREIGN KEY (Target, RoleKey) 
		REFERENCES <?php echo DB_PREFIX; ?>Roles(Player, RoleKey)
) CHARACTER SET latin1 COLLATE latin1_general_cs;

CREATE TABLE IF NOT EXISTS <?php echo DB_PREFIX; ?>Chats (
	Id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Game INT UNSIGNED NOT NULL,
	ChatRoom VARCHAR(8) NOT NULL,
	
	UNIQUE (Game, ChatRoom),
	FOREIGN KEY (Game) REFERENCES <?php echo DB_PREFIX; ?>Games(Id)
) CHARACTER SET latin1 COLLATE latin1_general_cs;

CREATE TABLE IF NOT EXISTS <?php echo DB_PREFIX; ?>ChatLog (
	Id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Chat INT UNSIGNED NOT NULL,
	User INT NOT NULL,
	Message TEXT NOT NULL,
	SendDate INT UNSIGNED NOT NULL,
	
	FOREIGN KEY (Chat) REFERENCES <?php echo DB_PREFIX; ?>Chats(Id),
	FOREIGN KEY (User) REFERENCES <?php echo DB_PREFIX; ?>UserStats(UserId)
) CHARACTER SET latin1 COLLATE latin1_general_cs;

CREATE TABLE IF NOT EXISTS <?php echo DB_PREFIX; ?>ChatPermission (
	Room INT UNSIGNED NOT NULL,
	RoleKey TEXT(8) NOT NULL,
	PEnable BOOLEAN NOT NULL,
	PWrite BOOLEAN NOT NULL,
	PVisible BOOLEAN NOT NULL,

	PRIMARY KEY (Room, RoleKey(8)),
	FOREIGN KEY (Room) REFERENCES <?php echo DB_PREFIX; ?>Chats(Id)
) CHARACTER SET latin1 COLLATE latin1_general_cs;

CREATE TABLE IF NOT EXISTS <?php echo DB_PREFIX; ?>VoteSetting (
	Chat INT UNSIGNED NOT NULL,
	VoteKey VARCHAR(5) NOT NULL,
	Created INT UNSIGNED NOT NULL,
	VoteStart INT NOT NULL,
	VoteEnd INT,
	EnabledUser TEXT NOT NULL,
	EnabledUserCount INT UNSIGNED NOT NULL,
	TargetUser TEXT NOT NULL,
	TargetUserCount INT UNSIGNED NOT NULL,
	ResultTarget INT UNSIGNED,
	
	PRIMARY KEY (Chat, VoteKey(5)),
	FOREIGN KEY (Chat) REFERENCES <?php echo DB_PREFIX; ?>Chats(Id),
	FOREIGN KEY (ResultTarget) REFERENCES <?php echo DB_PREFIX; ?>Player(Id)
) CHARACTER SET latin1 COLLATE latin1_general_cs;

CREATE TABLE IF NOT EXISTS <?php echo DB_PREFIX; ?>Votes (
	Setting INT UNSIGNED NOT NULL,
	VoteKey VARCHAR(5) NOT NULL,
	Voter INT UNSIGNED NOT NULL,
	Target INT UNSIGNED NOT NULL,
	VoteDate INT NOT NULL,
	
	PRIMARY KEY (Setting, VoteKey(5), Voter),
	-- FOREIGN KEY (Setting, VoteKey(5)) 
	-- 	REFERENCES <?php echo DB_PREFIX; ?>VoteSetting(Chat, VoteKey),
	FOREIGN KEY (Voter) REFERENCES <?php echo DB_PREFIX; ?>Player(Id),
	FOREIGN KEY (Target) REFERENCES <?php echo DB_PREFIX; ?>Player(Id)
) CHARACTER SET latin1 COLLATE latin1_general_cs;

