CREATE TABLE IF NOT EXISTS <?php echo DB_PREFIX; ?>Accounts (
	Id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name TEXT(20) NOT NULL,
	UNIQUE (Name(20))
) CHARACTER SET latin1 COLLATE latin1_general_cs;